from rest_framework import serializers
from api_medicamento_anvisa.apps.core.medicamento.models import Medicacao


class MedicacaoSerializer(serializers.ModelSerializer):
    class Meta:
        model = Medicacao
        fields = [
            'id',
            'substancia',
            'cnpj',
            'laboratorio',
            'codigo_ggrem',
            'registro',
            'ean_1',
            'ean_2',
            'produto',
            'apresentacao',
            'classe_terapeutica',
            'tipo_produto',
            'regime_preco',
            'pf_sem_impostos',
            'pf_0',
            'pf_12',
            'pf_12_alc',
            'pf_17',
            'pf_17_alc',
            'pf_17_5',
            'pf_17_5_alc',
            'pf_18',
            'pf_18_alc',
            'pf_19',
            'pf_19_alc',
            'pf_19_5',
            'pf_19_5_alc',
            'pf_20',
            'pf_20_alc',
            'pf_20_5',
            'pf_21',
            'pf_21_alc',
            'pf_22',
            'pf_22_alc',
            'pmc_sem_imposto',
            'pmc_0',
            'pmc_12',
            'pmc_12_alc',
            'pmc_17',
            'pmc_17_alc',
            'pmc_17_5',
            'pmc_17_5_alc',
            'pmc_18',
            'pmc_18_alc',
            'pmc_19',
            'pmc_19_alc',
            'pmc_19_5',
            'pmc_19_5_alc',
            'pmc_20',
            'pmc_20_alc',
            'pmc_20_5',
            'pmc_21',
            'pmc_21_alc',
            'pmc_22',
            'pmc_22_alc',
            'restricao_hospitalar',
            'cap',
            'confaz_87',
            'icms_0',
            'analise_recursal',
            'lista_concessao_credito',
            'comercializacao_2022',
            'tarja',
            'destinacao_comercial'
        ]
